### ISSUE TITLE
Invalid keyword argument "on-upper" - Any idea for fixing this error?

### ISSUE THREAD

**Issue by WeiZhang111** [pazner/Triplot.jl#2]
![image](https://user-images.githubusercontent.com/83143548/115987761-4a0a1780-a5ae-11eb-99a4-3f9a5f14fc0f.png)

**Comment by pazner** [comment]
What version of Julia are you running?

Also, this package is pretty out of date. If you want integration with Plots.jl, there is [TriplotRecipes](https://github.com/pazner/TriplotRecipes.jl) (which is what I would personally recommend), and for use with GR (most similar to this package) there is [TriplotGR](https://github.com/pazner/TriplotGR.jl).

**Comment by WeiZhang111** [comment]
Thank you so much. It has been fixed by setting environment of visual studio 2017! Thanks so much
